# Form implementation generated from reading ui file 'd:\MyNewWork\Yandex\MyNotes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MyNotes(object):
    def setupUi(self, MyNotes):
        MyNotes.setObjectName("MyNotes")
        MyNotes.resize(497, 382)
        self.centralwidget = QtWidgets.QWidget(parent=MyNotes)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.contactName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.contactName.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.contactName.setObjectName("contactName")
        self.contactNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.contactNumber.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.contactNumber.setObjectName("contactNumber")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.addContactBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addContactBtn.setGeometry(QtCore.QRect(240, 30, 171, 31))
        self.addContactBtn.setObjectName("addContactBtn")
        self.contactList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.contactList.setGeometry(QtCore.QRect(30, 90, 421, 251))
        self.contactList.setObjectName("contactList")
        MyNotes.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MyNotes)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 21))
        self.menubar.setObjectName("menubar")
        MyNotes.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MyNotes)
        self.statusbar.setObjectName("statusbar")
        MyNotes.setStatusBar(self.statusbar)

        self.retranslateUi(MyNotes)
        QtCore.QMetaObject.connectSlotsByName(MyNotes)

    def retranslateUi(self, MyNotes):
        _translate = QtCore.QCoreApplication.translate
        MyNotes.setWindowTitle(_translate("MyNotes", "MainWindow"))
        self.label.setText(_translate("MyNotes", "Имя"))
        self.label_2.setText(_translate("MyNotes", "Телефон"))
        self.addContactBtn.setText(_translate("MyNotes", "Добавить"))
