# Form implementation generated from reading ui file 'Yandex/newpil.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PIL20(object):
    def setupUi(self, PIL20):
        PIL20.setObjectName("PIL20")
        PIL20.resize(461, 381)
        self.centralwidget = QtWidgets.QWidget(parent=PIL20)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 70, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 120, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 170, 111, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 270, 161, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 270, 161, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 30, 241, 241))
        self.label.setObjectName("label")
        PIL20.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PIL20)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 21))
        self.menubar.setObjectName("menubar")
        PIL20.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=PIL20)
        self.statusbar.setObjectName("statusbar")
        PIL20.setStatusBar(self.statusbar)

        self.retranslateUi(PIL20)
        QtCore.QMetaObject.connectSlotsByName(PIL20)

    def retranslateUi(self, PIL20):
        _translate = QtCore.QCoreApplication.translate
        PIL20.setWindowTitle(_translate("PIL20", "MainWindow"))
        self.pushButton.setText(_translate("PIL20", "R"))
        self.pushButton_2.setText(_translate("PIL20", "G"))
        self.pushButton_3.setText(_translate("PIL20", "B"))
        self.pushButton_4.setText(_translate("PIL20", "ALL"))
        self.pushButton_5.setText(_translate("PIL20", "Против часовой стрелки"))
        self.pushButton_6.setText(_translate("PIL20", "По часовой стрелке"))
        self.label.setText(_translate("PIL20", "TextLabel"))
